[package]
name = "findomain"
version = "0.2.1"
authors = ["Eduard Toloza <tolosaeduard@gmail.com>"]
edition = "2018"
description = "The fastest and cross-platform subdomain enumerator, don't waste your time."
repository = "https://github.com/edu4rdshl/findomain"
license = "GPL-3.0-or-later"
keywords = ["findomain", "subdomain-discover", "find-subdomains"]
readme = "README.md"

[dependencies]
serde = { version = "1.0.98", features = ["derive"] }
serde_derive = "1.0.98"
reqwest = "0.9.19"
trust-dns-resolver = "0.11.1"
clap = { version = "2.33.0", features = ["yaml"] }
lazy_static = "1.3.0"
rand = "0.7.0"
url = "2.0.0"
# json = "0.11.14"

[target.arm-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10.24", features = ["vendored"] }

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.24", features = ["vendored"] }
